<a href="https://colab.research.google.com/github/Ramses-Monjaras/Data-Processing-Visualization/blob/main/Quiz_17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import requests
import pandas as pa
from bs4 import BeautifulSoup

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}
r = requests.get('https://en.wikipedia.org/wiki/List_of_highest_mountains_on_Earth', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")
tables = html_soup.find_all('table',class_="wikitable")

df1 = pa.read_html(str(tables))[0]
df1.head()

/tmp/ipykernel_6859/2530085760.py:13: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df1 = pa.read_html(str(tables))[0]

,Rank[i],Mountain name(s),Height (rounded)[ii],Prominence (rounded)[iii],Range,Coordinates[iv],Parent mountain [v],First ascent[vi],Country/ Region administered by[a],Image
0,1,Mount EverestSagarmathaChomolungma,"8,849 metres (29,032 ft) [c]","8,849 metres (29,032 ft)",Mahalangur Himalaya,27°59′17″N 86°55′30″E﻿ / ﻿27.9881°N 86.925°E,—N/a,1953,NepalChina,NaN
1,2,K2,"8,611 metres (28,251 ft)","4,020 metres (13,190 ft)",Baltoro Karakoram,35°52′53″N 76°30′48″E﻿ / ﻿35.88139°N 76.51333°E,Mount Everest,1954,PakistanChina[d][14],NaN
2,3,Kangchenjunga,"8,586 metres (28,169 ft)","3,922 metres (12,867 ft)",Kangchenjunga Himalaya,27°42′12″N 88°08′51″E﻿ / ﻿27.70333°N 88.14750°E *,Mount Everest,1955,NepalIndia,NaN
3,4,Lhotse,"8,516 metres (27,940 ft)","610 metres (2,000 ft)",Mahalangur Himalaya,27°57′42″N 86°55′59″E﻿ / ﻿27.96167°N 86.93306°E,Mount Everest,1956,ChinaNepal,NaN
4,5,Makalu,"8,485 metres (27,838 ft)","2,378 metres (7,802 ft)",Mahalangur Himalaya,27°53′23″N 87°05′20″E﻿ / ﻿27.88972°N 87.08889°E,Mount Everest,1955,NepalChina,NaN

In [6]:
df1.columns

Index(['Rank[i]', 'Mountain name(s)', 'Height (rounded)[ii]',
       'Prominence (rounded)[iii]', 'Range', 'Coordinates[iv]',
       'Parent mountain [v]', 'First ascent[vi]',
       'Country/ Region administered by[a]', 'Image'],
      dtype='object')

In [7]:
import re

def clean_column_name(col_name):
    col_name = re.sub(r'\[.*?\]', '', col_name)
    col_name = re.sub(r'\(.*?\)', '', col_name)
    col_name = re.sub(r'[^a-zA-Z0-9_]', '', col_name)
    col_name = re.sub(r'\s+', '_', col_name)
    col_name = col_name.strip().lower()
    return col_name

df1.columns = [clean_column_name(col) for col in df1.columns]

df1.head()

,rank,mountainname,height,prominence,range,coordinates,parentmountain,firstascent,countryregionadministeredby,image
0,1,Mount EverestSagarmathaChomolungma,"8,849 metres (29,032 ft) [c]","8,849 metres (29,032 ft)",Mahalangur Himalaya,27°59′17″N 86°55′30″E﻿ / ﻿27.9881°N 86.925°E,—N/a,1953,NepalChina,NaN
1,2,K2,"8,611 metres (28,251 ft)","4,020 metres (13,190 ft)",Baltoro Karakoram,35°52′53″N 76°30′48″E﻿ / ﻿35.88139°N 76.51333°E,Mount Everest,1954,PakistanChina[d][14],NaN
2,3,Kangchenjunga,"8,586 metres (28,169 ft)","3,922 metres (12,867 ft)",Kangchenjunga Himalaya,27°42′12″N 88°08′51″E﻿ / ﻿27.70333°N 88.14750°E *,Mount Everest,1955,NepalIndia,NaN
3,4,Lhotse,"8,516 metres (27,940 ft)","610 metres (2,000 ft)",Mahalangur Himalaya,27°57′42″N 86°55′59″E﻿ / ﻿27.96167°N 86.93306°E,Mount Everest,1956,ChinaNepal,NaN
4,5,Makalu,"8,485 metres (27,838 ft)","2,378 metres (7,802 ft)",Mahalangur Himalaya,27°53′23″N 87°05′20″E﻿ / ﻿27.88972°N 87.08889°E,Mount Everest,1955,NepalChina,NaN

Looking at the last column, I will remove the citations and split the country name like NepalChina to Nepal, China.